"""Personalised microbiome modifier suggestions for one demo user.

This module is the single source of truth the whole companion consumes. It is
generated from the user's `suggestions.xlsx` export and injected into the system
prompt so every reply is grounded in *this* user's results.

Schema of each suggestion:
- `score`  (float)  Signed strength of the recommendation.
                     * Sign  -> direction of the shift:
                         positive = a DESIRABLE shift (favour / increase this),
                         negative = an UNDESIRABLE outcome for the microbiome
                                    (limit / avoid this).
                     * Magnitude -> how strong AND how well-researched the
                       conclusion is. A large absolute value means high effect
                       size and high confidence; a small one means a weaker or
                       less certain signal.
- `name`   (str)    The modifier (food, probiotic strain, herb, nutrient,
                     diet style, supplement, ...). `{...}` holds the common name.
- `category` (str)  Which group the modifier belongs to.

Regenerate by re-running the import from a fresh `suggestions.xlsx` export.
"""

from __future__ import annotations

from typing import TypedDict


class Suggestion(TypedDict):
    score: float
    name: str
    category: str


# Full ranked list, highest (most desirable) score first.
SUGGESTIONS: list[Suggestion] = [
    {"score": 1883.4, "name": "Lacticaseibacillus casei {L. casei}", "category": "Probiotics"},
    {"score": 1773.8, "name": "Theobroma cacao {Cacao}", "category": "Food (excluding seasonings)"},
    {"score": 1605.4, "name": "Dodecanoic acid {Lauric acid}", "category": "Food (excluding seasonings)"},
    {"score": 1358.7, "name": "yogurt", "category": "Food (excluding seasonings)"},
    {"score": 1319.1, "name": "bifidobacterium longum,lactobacillus helveticus", "category": "Probiotics"},
    {"score": 1242.7, "name": "Trametes versicolor {Turkey tail}", "category": "Food (excluding seasonings)"},
    {"score": 1130.3, "name": "Silver nanoparticles {Colloidal silver}", "category": "Vitamins, Minerals and similar"},
    {"score": 1030.3, "name": "Ocimum basilicum {Basil}", "category": "Herb or Spice"},
    {"score": 1007.6, "name": "Lactose {Milk Sugar}", "category": "Sugar and similar"},
    {"score": 1004.0, "name": "Thymus vulgaris {thyme}", "category": "Herb or Spice"},
    {"score": 1003.9, "name": "rosmarinus officinalis {rosemary}", "category": "Herb or Spice"},
    {"score": 1000.4, "name": "Bovine Milk Products {Dairy}", "category": "Food (excluding seasonings)"},
    {"score": 982.8, "name": "Schinus molle {Peruvian pepper}", "category": "Herb or Spice"},
    {"score": 979.7, "name": "Handroanthus impetiginosus {pink trumpet tree}", "category": "Herb or Spice"},
    {"score": 976.8, "name": "2-(3,4-Dihydroxyphenyl)-5,7-dihydroxy-4H-chromen-4-one {Luteolin}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 973.5, "name": "Myristica fragrans {Nutmeg}", "category": "Food (excluding seasonings)"},
    {"score": 953.0, "name": "L-Theanine {Theanine}", "category": "Amino Acid and similar"},
    {"score": 906.3, "name": "Menta × piperita {peppermint}", "category": "Herb or Spice"},
    {"score": 904.6, "name": "allium sativum {garlic}", "category": "Herb or Spice"},
    {"score": 903.5, "name": "Riboflavin {Vitamin B2}", "category": "Vitamins, Minerals and similar"},
    {"score": 902.0, "name": "lactobacillus paracasei,lactobacillus acidophilus,bifidobacterium animalis", "category": "Probiotics"},
    {"score": 861.7, "name": "Humulus lupulus {Hops}", "category": "Food (excluding seasonings)"},
    {"score": 858.3, "name": "Metha family {Mint}", "category": "Herb or Spice"},
    {"score": 856.3, "name": "bacillus subtilis natto {B.natto}", "category": "Probiotics"},
    {"score": 832.9, "name": "2-aminoacetic acid {glycine}", "category": "Amino Acid and similar"},
    {"score": 827.4, "name": "Humulus lupulus compound {Xanthohumol}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 820.4, "name": "Prunus mume {Umeboshi}", "category": "Food (excluding seasonings)"},
    {"score": 820.1, "name": "Laurencia tristicha {Marine red algae}", "category": "Food (excluding seasonings)"},
    {"score": 819.8, "name": "Ribes nigrum {black currant}", "category": "Food (excluding seasonings)"},
    {"score": 794.0, "name": "Triticum aestivum {Whole-grain wheat}", "category": "Food (excluding seasonings)"},
    {"score": 782.0, "name": "Nigella sativa {black cumin}", "category": "Herb or Spice"},
    {"score": 770.7, "name": "Oenothera biennis {Evening Primrose Oil}", "category": "Herb or Spice"},
    {"score": 761.0, "name": "Cinnamomum zeylanicum {Ceylon Cinnamon}", "category": "Herb or Spice"},
    {"score": 746.1, "name": "ß-(1?4)-linked D-glucosamine and N-acetyl-D-glucosamine {Chitosan}", "category": "Sugar and similar"},
    {"score": 741.6, "name": "Eucalyptus {Gum Tree}", "category": "Food (excluding seasonings)"},
    {"score": 737.4, "name": "Citrus limon {Lemon}", "category": "Food (excluding seasonings)"},
    {"score": 730.0, "name": "Cymbopogon citratus {Lemongrass}", "category": "Herb or Spice"},
    {"score": 716.0, "name": "lactobacillus crispatus {L. Crispatus}", "category": "Probiotics"},
    {"score": 707.0, "name": "Perna canaliculus {Green-lipped mussel}", "category": "Food (excluding seasonings)"},
    {"score": 706.1, "name": "Pimpinella anisum {Anise}", "category": "Herb or Spice"},
    {"score": 701.0, "name": "Carum carvi {Caraway}", "category": "Food (excluding seasonings)"},
    {"score": 697.5, "name": "lactobacillus rhamnosus gg,bifidobacterium animalis lactis ,lactobacillus paracasei {cvs maximum strength probiotic}", "category": "Probiotics"},
    {"score": 684.7, "name": "Fraxinus angustifolia {Narrow-leaved ash}", "category": "Herb or Spice"},
    {"score": 674.2, "name": "Moringa Oleifera", "category": "Herb or Spice"},
    {"score": 668.9, "name": "Citrus aurantiifolia {Lime}", "category": "Food (excluding seasonings)"},
    {"score": 660.7, "name": "Sorghum {Broomcorn}", "category": "Food (excluding seasonings)"},
    {"score": 660.0, "name": "foeniculum vulgare,fennel", "category": "Herb or Spice"},
    {"score": 656.6, "name": "Urtica dioica {Stinging nettle}", "category": "Herb or Spice"},
    {"score": 653.9, "name": "Lactobacillus gasseri {L.gasseri}", "category": "Probiotics"},
    {"score": 652.4, "name": "Secale cereale {Rye}", "category": "Food (excluding seasonings)"},
    {"score": 650.1, "name": "Vsl#3 {Visibiome}", "category": "Probiotics"},
    {"score": 644.1, "name": "origanum vulgare {oregano}", "category": "Herb or Spice"},
    {"score": 640.2, "name": "Lentilactobacillus kefiri {Kefibios}", "category": "Probiotics"},
    {"score": 639.9, "name": "Decoction of Four Noble Drugs {Sijunzi Decoction (SJZD)}", "category": "Herb or Spice"},
    {"score": 630.2, "name": "bacillus licheniformis {b. licheniformis}", "category": "Probiotics"},
    {"score": 625.6, "name": "Olea europaea {Olive leaf}", "category": "Herb or Spice"},
    {"score": 623.4, "name": "Momordica charantia {Bitter gourd}", "category": "Herb or Spice"},
    {"score": 619.7, "name": "Limosilactobacillus fermentum {L. fermentum}", "category": "Probiotics"},
    {"score": 611.7, "name": "Galacto-oligosaccharides {GOS}", "category": "Prebiotics and similar"},
    {"score": 600.2, "name": "Amylum {Starch}", "category": "Diet Style"},
    {"score": 595.1, "name": "bifidobacterium", "category": "Probiotics"},
    {"score": 592.9, "name": "Hou-Po-Da-Huang-Tang {HPDHT}", "category": "Herb or Spice"},
    {"score": 592.6, "name": "Pentahydroxypentane {Xylitol}", "category": "Sugar and similar"},
    {"score": 591.7, "name": "arthamus tinctorius {Safflower}", "category": "Herb or Spice"},
    {"score": 590.1, "name": "tea", "category": "Food (excluding seasonings)"},
    {"score": 586.9, "name": "Cichorium intybus {Chicory}", "category": "Prebiotics and similar"},
    {"score": 579.7, "name": "Larrea tridentata {Chaparral}", "category": "Herb or Spice"},
    {"score": 578.7, "name": "Elaeis guineensis {Palm oil}", "category": "Food (excluding seasonings)"},
    {"score": 574.3, "name": "Coffee", "category": "Food (excluding seasonings)"},
    {"score": 563.8, "name": "sarcodiotheca gaudichaudii {Red Seaweed}", "category": "Food (excluding seasonings)"},
    {"score": 562.0, "name": "Levilactobacillus brevis {L.brevis}", "category": "Probiotics"},
    {"score": 556.3, "name": "Rosa canina {Rosehip}", "category": "Herb or Spice"},
    {"score": 552.3, "name": "Azadirachta indica {Neem}", "category": "Herb or Spice"},
    {"score": 552.0, "name": "Bacopa monnieri {Brahmi}", "category": "Herb or Spice"},
    {"score": 552.0, "name": "Plectranthus barbatus {Fumaric acid disodium salt}", "category": "Herb or Spice"},
    {"score": 549.4, "name": "ficus carica {fig}", "category": "Food (excluding seasonings)"},
    {"score": 539.4, "name": "Curcuma longa {Turmeric}", "category": "Food (excluding seasonings)"},
    {"score": 539.3, "name": "Limosilactobacillus reuteri {L. Reuteri}", "category": "Probiotics"},
    {"score": 535.9, "name": "Curcuma amada {Mango ginger}", "category": "Herb or Spice"},
    {"score": 534.0, "name": "Ruta {Rue}", "category": "Food (excluding seasonings)"},
    {"score": 533.6, "name": "Helianthus annuus {Sunflower}", "category": "Food (excluding seasonings)"},
    {"score": 525.1, "name": "synthetic disaccharide derivative of lactose {Lactulose}", "category": "Sugar and similar"},
    {"score": 523.3, "name": "Camel Milk", "category": "Food (excluding seasonings)"},
    {"score": 519.5, "name": "Bifidobacterium animalis {B. animalis}", "category": "Probiotics"},
    {"score": 517.9, "name": "Brassica juncea {Mustard greens}", "category": "Herb or Spice"},
    {"score": 508.2, "name": "Cola aspartame {Diet Cola}", "category": "Food (excluding seasonings)"},
    {"score": 506.6, "name": "α-Aminoglutaric acid {L-glutamic acid}", "category": "Food Preservatives"},
    {"score": 505.8, "name": "trachyspermum ammi {Ajwain}", "category": "Herb or Spice"},
    {"score": 505.7, "name": "Nattokinase {Natto}", "category": "Amino Acid and similar"},
    {"score": 505.4, "name": "Propolis {Bee glue}", "category": "Food (excluding seasonings)"},
    {"score": 504.9, "name": "Sinapis alba {yellow mustard}", "category": "Food (excluding seasonings)"},
    {"score": 503.6, "name": "resistant starch", "category": "Prebiotics and similar"},
    {"score": 503.1, "name": "Lacticaseibacillus paracasei shirota {Yakult}", "category": "Probiotics"},
    {"score": 499.6, "name": "kefir", "category": "Food (excluding seasonings)"},
    {"score": 497.8, "name": "Caffeine", "category": "Food (excluding seasonings)"},
    {"score": 497.6, "name": "Rhus chinensis {galla rhois}", "category": "Herb or Spice"},
    {"score": 481.6, "name": "Laser trilobum {Kefe cumin}", "category": "Herb or Spice"},
    {"score": 480.1, "name": "oligosaccharides {oligosaccharides}", "category": "Prebiotics and similar"},
    {"score": 479.3, "name": "Solanum tuberosum {Potatoes}", "category": "Food (excluding seasonings)"},
    {"score": 478.2, "name": "Rosa rugosa {Rugosa rose}", "category": "Herb or Spice"},
    {"score": 476.9, "name": "Petals from Punica granatum {pomegranate blossom tea}", "category": "Food (excluding seasonings)"},
    {"score": 474.5, "name": "Amorphophallus konjac {Konjaku flour}", "category": "Food (excluding seasonings)"},
    {"score": 472.0, "name": "Withania somnifera {Ashwagandha}", "category": "Herb or Spice"},
    {"score": 463.5, "name": "oplopanax horridus {Devil's Club}", "category": "Herb or Spice"},
    {"score": 460.9, "name": "Bacillus amyloliquefaciens {B.amyloliquefaciens }", "category": "Probiotics"},
    {"score": 457.2, "name": "long-term, moderate-intensity exercise {exercise}", "category": "Common and OTC Supplements"},
    {"score": 455.6, "name": "Diferuloylmethane {Curcumin}", "category": "Herb or Spice"},
    {"score": 455.6, "name": "Mimosoideae {Mimosa}", "category": "Herb or Spice"},
    {"score": 455.1, "name": "pediococcus acidilactic {RBB9 PEDIOCOCCUS ACIDILACTI}", "category": "Probiotics"},
    {"score": 451.5, "name": "Laurus nobilis {Bay Leaf}", "category": "Food (excluding seasonings)"},
    {"score": 447.9, "name": "alpha-linolenic acid {Omega-3}", "category": "Food (excluding seasonings)"},
    {"score": 445.8, "name": "Prunus dulcis {Almonds}", "category": "Food (excluding seasonings)"},
    {"score": 444.2, "name": "Kimchi", "category": "Food (excluding seasonings)"},
    {"score": 439.7, "name": "fat", "category": "Food (excluding seasonings)"},
    {"score": 437.7, "name": "2-aminoethanesulfonic acid {Taurine}", "category": "Amino Acid and similar"},
    {"score": 433.0, "name": "Saccharomyces cerevisiae var boulardii {S. boulardii}", "category": "Probiotics"},
    {"score": 432.4, "name": "Ipomoea batata {Purple sweet potatoes}", "category": "Food (excluding seasonings)"},
    {"score": 430.0, "name": "lactobacillus helveticus {L. helveticus}", "category": "Probiotics"},
    {"score": 428.2, "name": "Silybum marianum {milk thistle}", "category": "Herb or Spice"},
    {"score": 424.7, "name": "eugenol {Eugenic acid}", "category": "Herb or Spice"},
    {"score": 420.3, "name": "Pistacia vera {Pistachio}", "category": "Food (excluding seasonings)"},
    {"score": 415.0, "name": "Lactobacillus plantarum {L. plantarum}", "category": "Probiotics"},
    {"score": 407.8, "name": "Polyethylene oxide sorbitan mono-oleate {Polysorbate 80}", "category": "Food Preservatives"},
    {"score": 405.4, "name": "Crocus sativus {Saffron}", "category": "Herb or Spice"},
    {"score": 403.6, "name": "raffinose {sugar beet}", "category": "Sugar and similar"},
    {"score": 402.8, "name": "Salvia hispanica {Chia Seeds}", "category": "Food (excluding seasonings)"},
    {"score": 401.2, "name": "lidocaine hydrochloride,(prescription)", "category": "Common and OTC Supplements"},
    {"score": 401.1, "name": "2-hydroxypropane-1,2,3-tricarboxylic acid {Citric acid}", "category": "Food (excluding seasonings)"},
    {"score": 398.3, "name": "Salvia officinalis {Sage}", "category": "Herb or Spice"},
    {"score": 396.2, "name": "laminaria hyperborea {Cuvie}", "category": "Food (excluding seasonings)"},
    {"score": 395.9, "name": "chondrus crispus {Carrageen}", "category": "Food (excluding seasonings)"},
    {"score": 390.3, "name": "Anemopsis californica {Yerba mansa}", "category": "Herb or Spice"},
    {"score": 390.0, "name": "tomato powder", "category": "Food (excluding seasonings)"},
    {"score": 387.5, "name": "Tea tree", "category": "Food (excluding seasonings)"},
    {"score": 387.0, "name": "bifidobacterium longum {B.Longum }", "category": "Probiotics"},
    {"score": 382.0, "name": "Garcinia mangostana {Mangosteen}", "category": "Food (excluding seasonings)"},
    {"score": 381.3, "name": "bifidobacterium lactis,streptococcus thermophilus probiotic", "category": "Probiotics"},
    {"score": 377.2, "name": "Cuminum cyminum {Cumin}", "category": "Food (excluding seasonings)"},
    {"score": 374.7, "name": "3,5,7-trihydroxy flavanone-7-rhamnoglucoside {Hesperidin}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 373.6, "name": "Diospyros {Persimmon}", "category": "Food Preservatives"},
    {"score": 371.5, "name": "(3S,4R,5S)-1,3,4,5,6-Pentahydroxyhexan-2-one {Sorbose}", "category": "Food Preservatives"},
    {"score": 370.4, "name": "Artemisia absinthium {wormwood}", "category": "Herb or Spice"},
    {"score": 370.0, "name": "1,4-linked ß-D-xylopyranosyl {arabinoxylan}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 368.9, "name": "2-(3,4-Dihydroxyphenyl)-3,7-dihydroxychromen-4-one {Fisetin}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 363.8, "name": "wheat", "category": "Food (excluding seasonings)"},
    {"score": 361.2, "name": "1,2-dithiolane-3-pentanoic acid {a-Lipoic acid (ALA)}", "category": "Amino Acid and similar"},
    {"score": 356.6, "name": "Allium cepa {Onion}", "category": "Food (excluding seasonings)"},
    {"score": 352.9, "name": "D-(-)-Fructose {Fruit sugar}", "category": "Sugar and similar"},
    {"score": 352.0, "name": "Probiotic Mixture 1 {Japanese Vet Probiotic}", "category": "Probiotics"},
    {"score": 351.8, "name": "Bertholletia excelsa {Brazilian nuts}", "category": "Food (excluding seasonings)"},
    {"score": 350.2, "name": "Camellia sinensis {oolong tea}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 349.3, "name": "Arctium lappa {Burdock Root}", "category": "Food (excluding seasonings)"},
    {"score": 346.4, "name": "Magnesium Compounds {Magnesium supplements}", "category": "Vitamins, Minerals and similar"},
    {"score": 343.5, "name": "Sodium alginate", "category": "Amino Acid and similar"},
    {"score": 339.5, "name": "quebracho", "category": "Flavonoids, Polyphenols etc"},
    {"score": 333.0, "name": "Ginkgo biloba {Ginkgo}", "category": "Herb or Spice"},
    {"score": 331.3, "name": "D-ribofuranoside {Ribose}", "category": "Sugar and similar"},
    {"score": 329.7, "name": "Probiotic Mixture 2 {Vetafarm Probotic}", "category": "Probiotics"},
    {"score": 329.1, "name": "Pistacia lentiscus {mastic gum}", "category": "Prebiotics and similar"},
    {"score": 326.0, "name": "Musa acuminata {Banana}", "category": "Food (excluding seasonings)"},
    {"score": 325.8, "name": "Sodium benzoate {Sobenate}", "category": "Food Preservatives"},
    {"score": 325.1, "name": "Rhus coriaria {Sumac}", "category": "Herb or Spice"},
    {"score": 320.3, "name": "Escherichia coli Nissle 1917 {Mutaflor}", "category": "Probiotics"},
    {"score": 320.2, "name": "sodium butyrate", "category": "Common and OTC Supplements"},
    {"score": 315.4, "name": "Lonicera periclymenum {Epazote}", "category": "Food (excluding seasonings)"},
    {"score": 310.5, "name": "helichrysum italicum {Immortelle}", "category": "Herb or Spice"},
    {"score": 310.5, "name": "Micromeria fruticosa {White-leaved Savory}", "category": "Herb or Spice"},
    {"score": 309.6, "name": "Gallus domesticus {Chicken}", "category": "Food (excluding seasonings)"},
    {"score": 304.8, "name": "Citricidal {Grapefruit seed extract}", "category": "Food (excluding seasonings)"},
    {"score": 304.0, "name": "Sodium 2-stearoyllactate {sodium stearoyl lactylate}", "category": "Food Preservatives"},
    {"score": 303.6, "name": "Adeps suillus {Lard}", "category": "Food (excluding seasonings)"},
    {"score": 302.9, "name": "Gamma-Aminobutyric Acid {GABA}", "category": "Amino Acid and similar"},
    {"score": 301.9, "name": "Oryza sativa {Rice}", "category": "Food (excluding seasonings)"},
    {"score": 299.7, "name": "fructo-oligosaccharides", "category": "Prebiotics and similar"},
    {"score": 298.3, "name": "chlorhexidine", "category": "Common and OTC Supplements"},
    {"score": 295.3, "name": "Cathelicidin antimicrobial peptide {LL37}", "category": "Amino Acid and similar"},
    {"score": 294.3, "name": "Selenomethionine {Selenium supplement}", "category": "Vitamins, Minerals and similar"},
    {"score": 293.8, "name": "Cinnamaldehyde {Cinnamon Extract}", "category": "Herb or Spice"},
    {"score": 290.2, "name": "Euterpe oleracea {Acai}", "category": "Food (excluding seasonings)"},
    {"score": 286.4, "name": "Cinnamomum tamala {Indian bay leaf}", "category": "Herb or Spice"},
    {"score": 286.4, "name": "Lavandula angustifolia {lavender}", "category": "Herb or Spice"},
    {"score": 286.2, "name": "Leea indica {Bandicoot berry}", "category": "Herb or Spice"},
    {"score": 283.3, "name": "soy", "category": "Food (excluding seasonings)"},
    {"score": 282.1, "name": "Coriandrum sativum {Coriander}", "category": "Food (excluding seasonings)"},
    {"score": 276.4, "name": "Brassica oleracea var. italica {Broccoli}", "category": "Food (excluding seasonings)"},
    {"score": 275.9, "name": "Lacticaseibacillus rhamnosus {l. rhamnosus}", "category": "Probiotics"},
    {"score": 274.4, "name": "propyl gallate {E310}", "category": "Food Preservatives"},
    {"score": 272.9, "name": "Lacticaseibacillus paracasei {L.paracasei}", "category": "Probiotics"},
    {"score": 272.1, "name": "Zea mays {maize}", "category": "Food (excluding seasonings)"},
    {"score": 264.9, "name": "5,7-Dihydroxy-2-(4-hydroxyphenyl)-4H-1-benzopyran-4-one {Apigenin }", "category": "Flavonoids, Polyphenols etc"},
    {"score": 257.0, "name": "Actinidia deliciosa/chinensis {kiwifruit}", "category": "Food (excluding seasonings)"},
    {"score": 254.9, "name": "bacillus,lactobacillus,streptococcus,saccharomyces probiotic", "category": "Probiotics"},
    {"score": 249.9, "name": "Rheum × hybridum {Rhubarb}", "category": "Food (excluding seasonings)"},
    {"score": 246.0, "name": "dextromethorphan hydrobromide monohydrate,(prescription)", "category": "Common and OTC Supplements"},
    {"score": 245.7, "name": "Phaseolus vulgaris {Boston bean}", "category": "Food (excluding seasonings)"},
    {"score": 244.4, "name": "Faecalibacterium prausnitzii {Faecalibacterium prausnitzii}", "category": "Probiotics"},
    {"score": 240.9, "name": "(N-acetyl-p-aminophenol {TYLENOL}", "category": "Common and OTC Supplements"},
    {"score": 240.9, "name": "Allspice", "category": "Herb or Spice"},
    {"score": 228.3, "name": "Citrus Fruit Extract", "category": "Herb or Spice"},
    {"score": 226.3, "name": "Lactobacillus kefiranofaciens {Kefir Probiotic}", "category": "Probiotics"},
    {"score": 225.3, "name": "green tea", "category": "Food (excluding seasonings)"},
    {"score": 223.0, "name": "Pyroguaiac acid {Guaiacol}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 218.9, "name": "cetirizine dihydrochloride,(prescription)", "category": "Common and OTC Supplements"},
    {"score": 216.6, "name": "Inonotus obliquus {Chaga Mushroom}", "category": "Food (excluding seasonings)"},
    {"score": 213.2, "name": "magnolia officinalis {magnolia bark}", "category": "Herb or Spice"},
    {"score": 210.9, "name": "bacillus", "category": "Probiotics"},
    {"score": 202.8, "name": "3β-hydroxyurs-12-en-28-oic acid {Ursolic acid}", "category": "Amino Acid and similar"},
    {"score": 201.5, "name": "Polygonatum kingianum {Solomon's Seal}", "category": "Herb or Spice"},
    {"score": 199.9, "name": "Outer Layers of Triticum aestivum {Wheat Bran}", "category": "Food (excluding seasonings)"},
    {"score": 196.3, "name": "Shen Ling Bai Zhu San {参苓白术散}", "category": "Herb or Spice"},
    {"score": 196.1, "name": "Capra hircus milk {Goat milk}", "category": "Food (excluding seasonings)"},
    {"score": 195.0, "name": "lactobacillus plantarum,xylooligosaccharides,", "category": "Probiotics"},
    {"score": 193.5, "name": "N-Acetyl Cysteine {NAC}", "category": "Common and OTC Supplements"},
    {"score": 192.6, "name": "Capsicum annuum {Peppers} {Cayenne Pepper, Hot Pepper}", "category": "Food (excluding seasonings)"},
    {"score": 192.0, "name": "Rubus {Raspberries}", "category": "Food (excluding seasonings)"},
    {"score": 189.0, "name": "Blautia hansenii {Streptococcus hansenii}", "category": "Probiotics"},
    {"score": 188.4, "name": "Pentadigalloylglucose {Tannic Acid}", "category": "Herb or Spice"},
    {"score": 187.0, "name": "high-fat sucrose", "category": "Food (excluding seasonings)"},
    {"score": 180.8, "name": "naringenin {grapefruit}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 179.0, "name": "High-amylose maize starch {HAMS}", "category": "Prebiotics and similar"},
    {"score": 178.5, "name": "enterococcus faecium {E. faecium}", "category": "Probiotics"},
    {"score": 173.8, "name": "N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide {Melatonin}", "category": "Amino Acid and similar"},
    {"score": 170.4, "name": "polyphenols", "category": "Flavonoids, Polyphenols etc"},
    {"score": 168.3, "name": "Fragaria × ananassa {Strawberry}", "category": "Food (excluding seasonings)"},
    {"score": 167.7, "name": "low fodmap diet", "category": "Diet Style"},
    {"score": 166.6, "name": "bifidobacterium bifidum {B. bifidum}", "category": "Probiotics"},
    {"score": 166.5, "name": "Ocimum tenuiflorum {Tulsi}", "category": "Herb or Spice"},
    {"score": 166.2, "name": "N-L-a-aspartyl-L-phenylalanine methyl ester {aspartame}", "category": "Food Preservatives"},
    {"score": 166.1, "name": "alpha-tocopherol {Vitamin E}", "category": "Vitamins, Minerals and similar"},
    {"score": 160.5, "name": "(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethylcyclohex-1-en-1-yl)nona-2,4,6,8-tetraen-1-ol {Vitamin A}", "category": "Vitamins, Minerals and similar"},
    {"score": 157.9, "name": "vanillic acid {Vanilla}", "category": "Herb or Spice"},
    {"score": 156.9, "name": "Citrus polymethoxyflavone {Nobiletin (oranges and lemons)}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 149.7, "name": "High glycemic diet {High-sugar diet (HSD)}", "category": "Diet Style"},
    {"score": 147.1, "name": "4-O-a-glucopyranosyl-D-sorbitol {maltitol}", "category": "Amino Acid and similar"},
    {"score": 139.5, "name": "Hericium erinaceus {Lion's Mane Mushroom }", "category": "Food (excluding seasonings)"},
    {"score": 139.2, "name": "Phoenix dactylifera {dates}", "category": "Food (excluding seasonings)"},
    {"score": 137.4, "name": "3,3',4',5,7-pentahydroxyflavone {Quercetin}", "category": "Common and OTC Supplements"},
    {"score": 135.9, "name": "syzygium aromaticum {clove}", "category": "Herb or Spice"},
    {"score": 132.5, "name": "fucoidan {Brown Algae Extract}", "category": "Herb or Spice"},
    {"score": 132.3, "name": "Whole Cow milk {Whole Milk}", "category": "Food (excluding seasonings)"},
    {"score": 124.1, "name": "Conjugated Linoleic Acid {CLA}", "category": "Amino Acid and similar"},
    {"score": 120.9, "name": "Morinda citrifolia {Noni}", "category": "Herb or Spice"},
    {"score": 114.9, "name": "lactobacillus helveticus,lactobacillus rhamnosus", "category": "Probiotics"},
    {"score": 112.9, "name": "Bifidobacterium animalis subsp. lactis {B. Lactis}", "category": "Probiotics"},
    {"score": 112.8, "name": "omeprazole,(prescription)", "category": "Common and OTC Supplements"},
    {"score": 112.5, "name": "bacillus subtilis {B.Subtilis }", "category": "Probiotics"},
    {"score": 112.4, "name": "low-fat diets", "category": "Diet Style"},
    {"score": 112.2, "name": "bacillus subtilis,lactobacillus acidophilus", "category": "Probiotics"},
    {"score": 112.1, "name": "Carica papaya {papaya}", "category": "Food (excluding seasonings)"},
    {"score": 111.6, "name": "Sulforaphane {Dark Greens}", "category": "Food (excluding seasonings)"},
    {"score": 102.0, "name": "Lactiplantibacillus pentosus {L. pentosus}", "category": "Probiotics"},
    {"score": 101.9, "name": "arabinogalactan {arabinogalactan}", "category": "Prebiotics and similar"},
    {"score": 100.9, "name": "chitosan oligomers {chitooligosaccharides}", "category": "Prebiotics and similar"},
    {"score": 97.4, "name": "Palmitoylethanolamide {PEA}", "category": "Probiotics"},
    {"score": 97.2, "name": "Abelmoschus {Okra}", "category": "Food (excluding seasonings)"},
    {"score": 95.8, "name": "Ganoderma sichuanense {Reishi Mushroom}", "category": "Food (excluding seasonings)"},
    {"score": 89.3, "name": "Xanthomonas campestris {Xanthan gum}", "category": "Prebiotics and similar"},
    {"score": 88.5, "name": "Plantago {Psyllium}", "category": "Prebiotics and similar"},
    {"score": 87.8, "name": "Orange Juice", "category": "Food (excluding seasonings)"},
    {"score": 81.9, "name": "Sodium Chloride {Salt}", "category": "Food (excluding seasonings)"},
    {"score": 80.3, "name": "Blautia wexlerae {Blautia wexlerae}", "category": "Probiotics"},
    {"score": 78.6, "name": "Punica granatum {pomegranate}", "category": "Food (excluding seasonings)"},
    {"score": 78.3, "name": "Plantago asiatica {Obako}", "category": "Herb or Spice"},
    {"score": 76.3, "name": "Hibiscus {Rose mallow}", "category": "Food (excluding seasonings)"},
    {"score": 74.8, "name": "Xylaria hypoxylon {candlesnuff fungus}", "category": "Food (excluding seasonings)"},
    {"score": 71.0, "name": "Amorphophallus konjac {konjac}", "category": "Prebiotics and similar"},
    {"score": 69.3, "name": "Brassica oleracea {cabbage}", "category": "Food (excluding seasonings)"},
    {"score": 67.1, "name": "aspergillus oryzae {koji}", "category": "Probiotics"},
    {"score": 61.1, "name": "Quercetin-3-O-rutinoside {Rutin}", "category": "Flavonoids, Polyphenols etc"},
    {"score": 60.1, "name": "Petroselinum crispum {Parsley}", "category": "Food (excluding seasonings)"},
    {"score": 57.1, "name": "(2S)-2-amino-5-carbamimidamidopentanoic acid {arginine}", "category": "Amino Acid and similar"},
    {"score": 55.8, "name": "blueberry", "category": "Food (excluding seasonings)"},
    {"score": 55.2, "name": "methionine-choline-deficient diet {methionine-choline deprivation\" diet}", "category": "Diet Style"},
    {"score": 48.9, "name": "one form of diabetes diet {Moderate-carbohydrate diet}", "category": "Diet Style"},
    {"score": 48.6, "name": "Perilla frutescens {Perilla}", "category": "Herb or Spice"},
    {"score": 48.3, "name": "Dextrin", "category": "Prebiotics and similar"},
    {"score": 47.9, "name": "(2->1)-beta-D-fructofuranan {Inulin}", "category": "Prebiotics and similar"},
    {"score": 47.9, "name": "Vitex negundo {Nirgundi}", "category": "Herb or Spice"},
    {"score": 43.3, "name": "4-Guanidino-n-butyl syringate {Levan}", "category": "Amino Acid and similar"},
    {"score": 43.3, "name": "mixture of pancreas digestive enzymes {Pancreatin}", "category": "Common and OTC Supplements"},
    {"score": 43.2, "name": "oolong teas", "category": "Food (excluding seasonings)"},
    {"score": 41.9, "name": "Litchi chinensis {lychee fruit}", "category": "Food (excluding seasonings)"},
    {"score": 39.5, "name": "Piper nigrum {black pepper}", "category": "Herb or Spice"},
    {"score": 38.8, "name": "enterococcus durans {Streptococcus durans}", "category": "Probiotics"},
    {"score": 34.9, "name": "L-3-hydroxytrimethylaminobutanoate {carnitine}", "category": "Amino Acid and similar"},
    {"score": 34.1, "name": "Elettaria cardamomum {cardamom}", "category": "Herb or Spice"},
    {"score": 34.1, "name": "loratadine,(prescription)", "category": "Common and OTC Supplements"},
    {"score": 32.2, "name": "Mannan oligosaccharides {Mannooligosaccharide}", "category": "Prebiotics and similar"},
    {"score": 28.0, "name": "Cistus × incanus {Large Pink Cistus}", "category": "Herb or Spice"},
    {"score": 7.0, "name": "(2S)-2-amino-4-carbamoylbutanoic acid {Glutamine}", "category": "Amino Acid and similar"},
    {"score": -1.4, "name": "Trichosanic acid {pomegranate seed oil}", "category": "Amino Acid and similar"},
    {"score": -3.9, "name": "(2E,4E)-5-(1,3-Benzodioxol-5-yl)-1-(1-piperidinyl)-2,4-pentadien-1-one {Piperine}", "category": "Food (excluding seasonings)"},
    {"score": -5.0, "name": "Chrysanthemum × morifolium {Chrysanthemum}", "category": "Herb or Spice"},
    {"score": -5.1, "name": "Taraxacum officinale {Dandelion}", "category": "Food (excluding seasonings)"},
    {"score": -5.2, "name": "folate {Vitamin B9}", "category": "Vitamins, Minerals and similar"},
    {"score": -6.2, "name": "Streptococcus salivarius subsp. thermophilus {S. thermophilus}", "category": "Probiotics"},
    {"score": -6.5, "name": "Malus domestica {apple}", "category": "Food (excluding seasonings)"},
    {"score": -7.8, "name": "(RS)-2-(4-(2-methylpropyl)phenyl)propanoic acid {ibuprofen}", "category": "Common and OTC Supplements"},
    {"score": -8.0, "name": "5,6-dihydroxy-7-O-glucuronide flavone {Baicalin }", "category": "Herb or Spice"},
    {"score": -8.6, "name": "Fagopyrum esculentum {Buckwheat}", "category": "Food (excluding seasonings)"},
    {"score": -9.5, "name": "red wine", "category": "Food (excluding seasonings)"},
    {"score": -9.6, "name": "Brevibacillus laterosporus {B. laterosporus }", "category": "Probiotics"},
    {"score": -10.3, "name": "(R)-(6-methoxyquinolin-4-yl)((2S,4S,8R)-8-vinylquinuclidin-2-yl)methanol {Quinine}", "category": "Herb or Spice"},
    {"score": -10.4, "name": "2-Methyl-5-(1-methylethyl)phenol {Carvacrol}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -10.6, "name": "Lupinus {Lupin[Warning]}", "category": "Food (excluding seasonings)"},
    {"score": -10.9, "name": "Traditional Mediterranean diet {Mediterranean diet}", "category": "Diet Style"},
    {"score": -11.6, "name": "dietary fiber", "category": "Diet Style"},
    {"score": -12.6, "name": "walnuts", "category": "Food (excluding seasonings)"},
    {"score": -13.2, "name": "Thiamine {Vitamin B1}", "category": "Vitamins, Minerals and similar"},
    {"score": -13.6, "name": "Panax ... {Ginseng}", "category": "Herb or Spice"},
    {"score": -13.7, "name": "Pantothenic acid {Vitamin B5}", "category": "Vitamins, Minerals and similar"},
    {"score": -13.7, "name": "ß-glucan {Beta-Glucan}", "category": "Prebiotics and similar"},
    {"score": -13.9, "name": "5,6-dihydro-9,10-dimethoxybenzo[g]-1,3-benzodioxolo[5,6-a]quinolizinium {Berberine}", "category": "Herb or Spice"},
    {"score": -14.6, "name": "Fiber, total dietary", "category": "Diet Style"},
    {"score": -14.9, "name": "schisandra chinensis {magnolia berry}", "category": "Herb or Spice"},
    {"score": -15.2, "name": "eicosapentaenoic acid (EPA),docosahexaenoic acid (DHA) {Fish Oil}", "category": "Food (excluding seasonings)"},
    {"score": -15.2, "name": "Pleurotus ostreatus {Oyster mushroom}", "category": "Food (excluding seasonings)"},
    {"score": -15.3, "name": "Akkermansia muciniphila {Pendulum Probiotic}", "category": "Probiotics"},
    {"score": -15.5, "name": "Boron {Borax}", "category": "Common and OTC Supplements"},
    {"score": -15.6, "name": "Nicotine, Nicotine Patch", "category": "Food (excluding seasonings)"},
    {"score": -15.8, "name": "High-fibre diet {Whole food diet}", "category": "Diet Style"},
    {"score": -16.3, "name": "xylooligosaccharide", "category": "Prebiotics and similar"},
    {"score": -16.5, "name": "fruit", "category": "Food (excluding seasonings)"},
    {"score": -16.5, "name": "Human milk oligosaccharides (prebiotic, Holigos, Stachyose)", "category": "Prebiotics and similar"},
    {"score": -16.8, "name": "fruit/legume fibre", "category": "Food (excluding seasonings)"},
    {"score": -17.1, "name": "brown algae", "category": "Food (excluding seasonings)"},
    {"score": -17.2, "name": "Heyndrickxia coagulans {B. coagulans}", "category": "Probiotics"},
    {"score": -17.6, "name": "Hydrastis canadensis {Goldenseal}", "category": "Food (excluding seasonings)"},
    {"score": -17.7, "name": "Ocimum gratissimum {Clove basil}", "category": "Herb or Spice"},
    {"score": -17.9, "name": "Far Infrared Therapy {Far infrared Sauna }", "category": "Food (excluding seasonings)"},
    {"score": -18.1, "name": "Camellia Linnaeus {camellia}", "category": "Herb or Spice"},
    {"score": -18.1, "name": "gynostemma pentaphyllum {Jiaogulan}", "category": "Herb or Spice"},
    {"score": -18.1, "name": "whole-grain diet", "category": "Diet Style"},
    {"score": -18.3, "name": "Dysphania ambrosioides {Epazote}", "category": "Food (excluding seasonings)"},
    {"score": -18.5, "name": "Parabacteroides goldsteinii {Parabacteroides goldsteinii}", "category": "Probiotics"},
    {"score": -19.6, "name": "glycyrrhizic acid {licorice}", "category": "Herb or Spice"},
    {"score": -20.4, "name": "Slow digestible carbohydrates. {Low Glycemic}", "category": "Diet Style"},
    {"score": -21.8, "name": "Lycium barbarum x Lycium chinense, {Goji Fruit, Juice}", "category": "Food (excluding seasonings)"},
    {"score": -23.2, "name": "Bifidobacterium breve {B. breve}", "category": "Probiotics"},
    {"score": -24.0, "name": "3,5,7-trihydroxy-2-(4-hydroxyphenyl)chromen-4-one {kaempferol}", "category": "Amino Acid and similar"},
    {"score": -26.3, "name": "Chamaemelum nobile {Camomile}", "category": "Herb or Spice"},
    {"score": -28.4, "name": "D-mannitol {Mannitol}", "category": "Amino Acid and similar"},
    {"score": -29.5, "name": "Lactobacillus mucosae", "category": "Probiotics"},
    {"score": -30.2, "name": "Catechol {Catecholamines}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -30.3, "name": "Ananas comosus {Pineapple}", "category": "Food (excluding seasonings)"},
    {"score": -31.8, "name": "grape seed extract", "category": "Herb or Spice"},
    {"score": -32.5, "name": "Terminalia chebula {Haritaki}", "category": "Herb or Spice"},
    {"score": -32.7, "name": "2-Aminopentanedioic acid {glutamate}", "category": "Food Preservatives"},
    {"score": -33.6, "name": "α-alanine {alanine}", "category": "Amino Acid and similar"},
    {"score": -34.2, "name": "Armoracia rusticana {Horseradish}", "category": "Food (excluding seasonings)"},
    {"score": -34.3, "name": "Tudca", "category": "Common and OTC Supplements"},
    {"score": -35.6, "name": "Bupleurum falcatum x Scutellaria baicalensis x Paeoniae radix {daesiho-tang}", "category": "Herb or Spice"},
    {"score": -36.6, "name": "Pisces {Fish}", "category": "Food (excluding seasonings)"},
    {"score": -37.7, "name": "cobalamin {Vitamin B-12}", "category": "Vitamins, Minerals and similar"},
    {"score": -38.2, "name": "Epicatechin {Green tea polyphenol}", "category": "Amino Acid and similar"},
    {"score": -39.7, "name": "Cucurbita pepo {Pumpkin}", "category": "Food (excluding seasonings)"},
    {"score": -41.8, "name": "Rubia cordifolia {Indian madder}", "category": "Herb or Spice"},
    {"score": -42.2, "name": "Low Erucic Acid Rapeseed {Canola Oil}", "category": "Food (excluding seasonings)"},
    {"score": -43.3, "name": "cadmium", "category": "Vitamins, Minerals and similar"},
    {"score": -49.0, "name": "Sucralose {Splenda}", "category": "Sugar and similar"},
    {"score": -53.1, "name": "Glyceryl guaiacolate {Guaifenesin}", "category": "Common and OTC Supplements"},
    {"score": -55.0, "name": "Manganese sulfate {Manganese Supplement}", "category": "Vitamins, Minerals and similar"},
    {"score": -57.0, "name": "Arachis hypogaea {Peanut}", "category": "Food (excluding seasonings)"},
    {"score": -60.5, "name": "low-fat high-complex carbohydrate diet", "category": "Diet Style"},
    {"score": -61.2, "name": "a-Gluco-oligosaccharides {GOS}", "category": "Prebiotics and similar"},
    {"score": -61.4, "name": "Bacteriophages LH01,T4D,LL12,LL5 {PreforPro}", "category": "Prebiotics and similar"},
    {"score": -61.5, "name": "ß-Carotene {Carrots}", "category": "Food (excluding seasonings)"},
    {"score": -68.5, "name": "Grape Polyphenols {Grape Flavonoids}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -69.5, "name": "Eutrema japonicum {wasabi}", "category": "Food (excluding seasonings)"},
    {"score": -69.7, "name": "Asparagus officinalis {Asparagus}", "category": "Food (excluding seasonings)"},
    {"score": -71.9, "name": "Sus domesticus {Pork}", "category": "Food (excluding seasonings)"},
    {"score": -77.0, "name": "resveratrol-pterostilbene x Quercetin {quercetin x resveratrol}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -77.1, "name": "Mentha spicata {Spearmint}", "category": "Herb or Spice"},
    {"score": -77.7, "name": "Cannabis sativa seed oil {Hemp Oil}", "category": "Food (excluding seasonings)"},
    {"score": -83.2, "name": "A dairy product produced by coagulation of the milk protein casein {Cheese}", "category": "Food (excluding seasonings)"},
    {"score": -84.0, "name": "A2 variant of beta-casein {A2 Milk}", "category": "Food (excluding seasonings)"},
    {"score": -84.9, "name": "high-fat diets", "category": "Diet Style"},
    {"score": -85.1, "name": "Hypericum perforatum {St. John's Wort}", "category": "Herb or Spice"},
    {"score": -85.2, "name": "diosmin {diosmin}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -90.0, "name": "bifidobacterium pseudocatenulatum {B. pseudocatenulatum }", "category": "Probiotics"},
    {"score": -90.6, "name": "Acacia senegal {gum arabic}", "category": "Prebiotics and similar"},
    {"score": -91.9, "name": "β-lactoglobulin {Whey}", "category": "Food (excluding seasonings)"},
    {"score": -104.1, "name": "Pine pollen", "category": "Food (excluding seasonings)"},
    {"score": -108.1, "name": "Flavan-3-ols {Epicatechin}", "category": "Food (excluding seasonings)"},
    {"score": -109.8, "name": "nuts", "category": "Food (excluding seasonings)"},
    {"score": -123.6, "name": "Lycopene {Glucosamine (GS)}", "category": "Amino Acid and similar"},
    {"score": -125.2, "name": "Sesamum indicum {Sesame}", "category": "Food (excluding seasonings)"},
    {"score": -126.4, "name": "Beta vulgaris {Beet}", "category": "Food (excluding seasonings)"},
    {"score": -127.7, "name": "Bifidobacterium catenulatum subsp. catenulatum {Bifidobacterium catenulatum}", "category": "Probiotics"},
    {"score": -133.0, "name": "Pisum sativum {pea}", "category": "Diet Style"},
    {"score": -143.0, "name": "N-acetylneuraminic acid {Sialic acid}", "category": "Sugar and similar"},
    {"score": -143.3, "name": "lactobacillus rhamnosus gg", "category": "Probiotics"},
    {"score": -143.4, "name": "Cannabis sativa {Marijuana}", "category": "Herb or Spice"},
    {"score": -143.9, "name": "Coenzyme Q10 {CoQ 10}", "category": "Herb or Spice"},
    {"score": -145.8, "name": "Arctostaphylos uva-ursi {Bearberry}", "category": "Food (excluding seasonings)"},
    {"score": -146.3, "name": "Rubus fruticosus {Blackberry}", "category": "Food (excluding seasonings)"},
    {"score": -147.1, "name": "Bacillus amyloliquefaciens group {B. Amyloliquefaciens}", "category": "Probiotics"},
    {"score": -147.7, "name": "ascorbic acid {Vitamin C}", "category": "Vitamins, Minerals and similar"},
    {"score": -150.5, "name": "Lactobacillus Johnsonii {Lactobacillus Johnsonii}", "category": "Probiotics"},
    {"score": -151.1, "name": "Prunus avium {Cherry}", "category": "Food (excluding seasonings)"},
    {"score": -152.5, "name": "Vanillin {Vanilla}", "category": "Herb or Spice"},
    {"score": -168.0, "name": "acetylsalicylic acid,aspirin", "category": "Common and OTC Supplements"},
    {"score": -168.4, "name": "vegetable", "category": "Food (excluding seasonings)"},
    {"score": -169.7, "name": "Apium graveolens {Celery}", "category": "Food (excluding seasonings)"},
    {"score": -175.4, "name": "Morus {Mulberry }", "category": "Food (excluding seasonings)"},
    {"score": -175.7, "name": "ß-2,6-polyfructose {Levan}", "category": "Sugar and similar"},
    {"score": -185.4, "name": "Zingiber officinale Roscoe {ginger}", "category": "Herb or Spice"},
    {"score": -187.2, "name": "Monascus purpureus x Oryza sativa {Red yeast rice}", "category": "Herb or Spice"},
    {"score": -187.5, "name": "Agaricus bisporus {White button mushrooms}", "category": "Food (excluding seasonings)"},
    {"score": -188.0, "name": "Propionic acid {Propionate}", "category": "Food Preservatives"},
    {"score": -196.4, "name": "Kluyveromyces marxianus (yeast)", "category": "Probiotics"},
    {"score": -196.9, "name": "Streptococcus faecalis, Clostridium butyricum, Bacillus mesentericus {Bio-three}", "category": "Probiotics"},
    {"score": -198.7, "name": "Arthrospira platensis {Spirulina}", "category": "Herb or Spice"},
    {"score": -201.0, "name": "5-Hydroxytryptophan {5-HTP}", "category": "Common and OTC Supplements"},
    {"score": -202.6, "name": "bifidobacterium infantis {B. infantis}", "category": "Probiotics"},
    {"score": -202.8, "name": "resveratrol-pterostilbene {grapes, blueberries}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -203.8, "name": "Plant-based diet {Vegetarian diet}", "category": "Diet Style"},
    {"score": -205.9, "name": "Bromelain {Bromelin}", "category": "Common and OTC Supplements"},
    {"score": -206.6, "name": "Linum usitatissimum {Flaxseed}", "category": "Food (excluding seasonings)"},
    {"score": -208.0, "name": "Carrageenans {Carrageenan}", "category": "Prebiotics and similar"},
    {"score": -215.7, "name": "Ayurvedic herbal formula {Triphala}", "category": "Herb or Spice"},
    {"score": -218.4, "name": "2-Amino-5-(carbamoylamino)pentanoic acid {Citrulline}", "category": "Amino Acid and similar"},
    {"score": -226.6, "name": "Genista tinctoria {Genistein}", "category": "Amino Acid and similar"},
    {"score": -229.0, "name": "glutathione", "category": "Flavonoids, Polyphenols etc"},
    {"score": -231.5, "name": "Boswellia serrata {Boswellia}", "category": "Herb or Spice"},
    {"score": -240.9, "name": "Lactobacillus jensenii {L Jensenii}", "category": "Probiotics"},
    {"score": -241.4, "name": "high carbohydrate diet", "category": "Diet Style"},
    {"score": -245.4, "name": "Honey {Honey }", "category": "Food (excluding seasonings)"},
    {"score": -255.6, "name": "Bacteroides uniformis {Bacteroides uniformis}", "category": "Probiotics"},
    {"score": -264.1, "name": "terpenophenolics {cannabinoids}", "category": "Herb or Spice"},
    {"score": -265.5, "name": "steviol glycosides {Stevia}", "category": "Sugar and similar"},
    {"score": -265.8, "name": "coptis chinensis {Chinese goldthread }", "category": "Herb or Spice"},
    {"score": -266.0, "name": "isoflavones {Dietary phytoestrogens}", "category": "Food (excluding seasonings)"},
    {"score": -275.7, "name": "Pulses, Beans", "category": "Food (excluding seasonings)"},
    {"score": -280.1, "name": "Sambucus nigra L. ssp. canadensis {Elderberry}", "category": "Food (excluding seasonings)"},
    {"score": -282.0, "name": "non-starch polysaccharides", "category": "Sugar and similar"},
    {"score": -283.5, "name": "Lactotransferrin {Lactoferrin}", "category": "Amino Acid and similar"},
    {"score": -286.8, "name": "Latilactobacillus sakei {Lactobacillus sakei}", "category": "Probiotics"},
    {"score": -287.3, "name": "Menaquinone K2 {Vitamin K}", "category": "Vitamins, Minerals and similar"},
    {"score": -292.0, "name": "Lactococcus lactis {Streptococcus lactis}", "category": "Probiotics"},
    {"score": -295.1, "name": "Mixture of Vitamin B? {B Vitamins}", "category": "Vitamins, Minerals and similar"},
    {"score": -296.7, "name": "4-hydroxyphenyl-beta-D-glucopyranoside {Arbutin}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -299.7, "name": "partially hydrolysed guar gum", "category": "Prebiotics and similar"},
    {"score": -301.1, "name": "2H-1?6,2-benzothiazol-1,1,3-trione {Saccharin}", "category": "Food Preservatives"},
    {"score": -317.6, "name": "Aloe vera {True Aloe}", "category": "Food (excluding seasonings)"},
    {"score": -328.4, "name": "Lentilactobacillus buchneri {Lactobacillus buchneri}", "category": "Probiotics"},
    {"score": -330.6, "name": "Ethanoic acid {Vinegar}", "category": "Amino Acid and similar"},
    {"score": -337.3, "name": "Phyllanthus emblica {Chinese gall}", "category": "Herb or Spice"},
    {"score": -344.7, "name": "oligofructose-enriched inulin", "category": "Prebiotics and similar"},
    {"score": -353.9, "name": "Hordeum vulgare {Barley}", "category": "Food (excluding seasonings)"},
    {"score": -355.9, "name": "laminaria digitata {Oarweed}", "category": "Food (excluding seasonings)"},
    {"score": -358.2, "name": "cellulose", "category": "Prebiotics and similar"},
    {"score": -372.6, "name": "Glycine max x Aspergillus oryzae {Miso}", "category": "Food (excluding seasonings)"},
    {"score": -373.6, "name": "Glycine max {Doenjang}", "category": "Food (excluding seasonings)"},
    {"score": -375.2, "name": "a-Amino-3-indolepropionic acid {Tryptophan}", "category": "Amino Acid and similar"},
    {"score": -381.9, "name": "Astragalus", "category": "Food (excluding seasonings)"},
    {"score": -387.9, "name": "1,4-a-D-glucan branched {Amylopectin}", "category": "Common and OTC Supplements"},
    {"score": -392.8, "name": "ascophyllum nodosum {Rockweed}", "category": "Food (excluding seasonings)"},
    {"score": -394.1, "name": "henopodium quinoa {Quinoa}", "category": "Food (excluding seasonings)"},
    {"score": -399.8, "name": "grapes", "category": "Food (excluding seasonings)"},
    {"score": -409.1, "name": "Disodium fumarate {Fumaric acid disodium salt}", "category": "Food Preservatives"},
    {"score": -419.6, "name": "vitamin d", "category": "Vitamins, Minerals and similar"},
    {"score": -423.7, "name": "Alkalihalobacillus clausii {Bacillus clausii }", "category": "Probiotics"},
    {"score": -425.5, "name": "Dendrobium officinale Kimura {Tiepishihu}", "category": "Herb or Spice"},
    {"score": -429.3, "name": "Myrciaria dubia {Camu camu}", "category": "Herb or Spice"},
    {"score": -432.3, "name": "Pediococcus pentosaceus {P. pentosaceus}", "category": "Probiotics"},
    {"score": -437.8, "name": "Codonopsis pilosula {Dangshen}", "category": "Herb or Spice"},
    {"score": -444.9, "name": "hypocaloric hyperproteic diet", "category": "Diet Style"},
    {"score": -445.7, "name": "Enterococcus faecalis {Streptococcus faecalis}", "category": "Probiotics"},
    {"score": -453.4, "name": "colostrum", "category": "Common and OTC Supplements"},
    {"score": -464.8, "name": "2-Amino-4-(methylthio)butanoic acid {Methionine}", "category": "Flavonoids, Polyphenols etc"},
    {"score": -468.3, "name": "Trigonella foenum-graecum {Fenugreek}", "category": "Herb or Spice"},
    {"score": -476.7, "name": "N,N,N-trimethylglycine {Betaine}", "category": "Amino Acid and similar"},
    {"score": -479.2, "name": "Crataegus {Hawthorn}", "category": "Herb or Spice"},
    {"score": -496.5, "name": "Sodium Bicarbonate {Baking Soda}", "category": "Common and OTC Supplements"},
    {"score": -509.8, "name": "Lithium carbonate {Lithium}", "category": "Vitamins, Minerals and similar"},
    {"score": -519.0, "name": "Enterococcus faecium sf 68 {bioflorin}", "category": "Probiotics"},
    {"score": -521.0, "name": "Avena sativa {Oats}", "category": "Food (excluding seasonings)"},
    {"score": -528.0, "name": "Sodium hypochlorite {Chlorinated Drinking Water}", "category": "Vitamins, Minerals and similar"},
    {"score": -538.2, "name": "Poly[β-D-xylopyranose(1->4)] {Xylan}", "category": "Prebiotics and similar"},
    {"score": -549.1, "name": "low carbohydrate diet", "category": "Diet Style"},
    {"score": -553.5, "name": "restricted-fiber diet {low fiber diet}", "category": "Diet Style"},
    {"score": -555.7, "name": "Echinacea Moench {Echinacea}", "category": "Food (excluding seasonings)"},
    {"score": -561.2, "name": "Finnish Probiotic {Valio Probiotic}", "category": "Probiotics"},
    {"score": -561.6, "name": "Biotin {Vitamin B7}", "category": "Vitamins, Minerals and similar"},
    {"score": -563.6, "name": "refined wheat breads", "category": "Food (excluding seasonings)"},
    {"score": -577.7, "name": "pyrrolidine-2-carboxylic acid {proline}", "category": "Amino Acid and similar"},
    {"score": -585.4, "name": "N-(aminoiminomethyl)-N methyl glycine {Creatine}", "category": "Common and OTC Supplements"},
    {"score": -591.8, "name": "Clostridium butyricum MIYAIRI 588 {Miyarisan}", "category": "Probiotics"},
    {"score": -624.1, "name": "Bacillus pumilus {B. pumilus}", "category": "Probiotics"},
    {"score": -626.4, "name": "Lactiplantibacillus argentoratensis {Lactobacillus argentoratensis}", "category": "Probiotics"},
    {"score": -633.1, "name": "Potassium iodide {Iodine Supplement}", "category": "Vitamins, Minerals and similar"},
    {"score": -647.3, "name": "Bixa orellana {annatto }", "category": "Herb or Spice"},
    {"score": -656.0, "name": "gliadin, glutenin etc {Gluten}", "category": "Food (excluding seasonings)"},
    {"score": -658.2, "name": "low protein diet", "category": "Diet Style"},
    {"score": -674.0, "name": "D-glucose {Glucose}", "category": "Sugar and similar"},
    {"score": -677.4, "name": "2-hydroxyethyl)trimethylazanium {choline}", "category": "Amino Acid and similar"},
    {"score": -681.1, "name": "pseudo-cereals {amaranth,quinoa, taro,buckwheat}", "category": "Food (excluding seasonings)"},
    {"score": -689.7, "name": "Abstention from eating {Fasting}", "category": "Food (excluding seasonings)"},
    {"score": -722.8, "name": "high-saturated fat diet", "category": "Diet Style"},
    {"score": -724.8, "name": "Avena sativa x Hordeum vulgare {barley,oat}", "category": "Food (excluding seasonings)"},
    {"score": -735.5, "name": "Lentinula edodes {Shiitake Mushroom}", "category": "Food (excluding seasonings)"},
    {"score": -762.5, "name": "2-Amino-3-(4-hydroxyphenyl)propanoic acid {Tyrosine}", "category": "Amino Acid and similar"},
    {"score": -773.4, "name": "Vaccinium {Cranberry}", "category": "Food (excluding seasonings)"},
    {"score": -778.8, "name": "Vaccinium vitis-idaea {lingonberries}", "category": "Food (excluding seasonings)"},
    {"score": -783.8, "name": "Tributyrin", "category": "Common and OTC Supplements"},
    {"score": -801.2, "name": "olive oil {olive oil}", "category": "Food (excluding seasonings)"},
    {"score": -806.8, "name": "amaranthus {amaranth}", "category": "Food (excluding seasonings)"},
    {"score": -811.4, "name": "Agave salmiana {Agavins}", "category": "Sugar and similar"},
    {"score": -825.3, "name": "ketogenic diet", "category": "Diet Style"},
    {"score": -830.6, "name": "Dihydroquercetin {Taxifolin}", "category": "Amino Acid and similar"},
    {"score": -856.2, "name": "Ferrum {Iron Supplements}", "category": "Vitamins, Minerals and similar"},
    {"score": -882.7, "name": "Vaccinium myrtillus {Bilberry}", "category": "Food (excluding seasonings)"},
    {"score": -896.3, "name": "nicotinic acid {Vitamin B-3}", "category": "Vitamins, Minerals and similar"},
    {"score": -910.6, "name": "Fiber of Vitis vinifera {Grape Fiber}", "category": "Diet Style"},
    {"score": -949.0, "name": "Under cookded animal protein {Rare meat}", "category": "Food (excluding seasonings)"},
    {"score": -950.4, "name": "bifidobacterium pseudocatenulatum li09,bifidobacterium catenulatum li10", "category": "Probiotics"},
    {"score": -986.7, "name": "Ceratonia siliqua {carob}", "category": "Food (excluding seasonings)"},
    {"score": -993.4, "name": "Glycerol", "category": "Food (excluding seasonings)"},
    {"score": -995.4, "name": "Ulmus rubra {slippery elm}", "category": "Herb or Spice"},
    {"score": -1051.0, "name": "Pulvis ledebouriellae compositae {Bofutsushosan}", "category": "Herb or Spice"},
    {"score": -1082.6, "name": "pectin {pectin}", "category": "Food (excluding seasonings)"},
    {"score": -1122.8, "name": "d-galactose {milk sugar}", "category": "Sugar and similar"},
    {"score": -1128.9, "name": "high red meat", "category": "Food (excluding seasonings)"},
    {"score": -1264.1, "name": "Polydextrose {polydextrose}", "category": "Sugar and similar"},
    {"score": -1387.5, "name": "High-protein diet {Atkins low-carbohydrate diet}", "category": "Diet Style"},
    {"score": -1396.0, "name": "vegetarians", "category": "Food (excluding seasonings)"},
]


def recommended(limit: int | None = None) -> list[Suggestion]:
    """Desirable modifiers (positive score), strongest first."""
    items = [s for s in SUGGESTIONS if s["score"] > 0]
    return items[:limit] if limit else items


def avoid(limit: int | None = None) -> list[Suggestion]:
    """Undesirable modifiers (negative score), strongest first."""
    items = sorted(
        (s for s in SUGGESTIONS if s["score"] < 0),
        key=lambda s: s["score"],
    )
    return items[:limit] if limit else items


def categories() -> list[str]:
    """Distinct categories present in the suggestions, in first-seen order."""
    seen: list[str] = []
    for s in SUGGESTIONS:
        if s["category"] not in seen:
            seen.append(s["category"])
    return seen


def summary() -> str:
    """One-line snapshot of the suggestion set."""
    rec, avd = recommended(), avoid()
    return (
        f"{len(SUGGESTIONS)} personalised modifiers across {len(categories())} "
        f"categories: {len(rec)} to favour, {len(avd)} to limit."
    )
